# Generated by Django 5.2.8 on 2025-11-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('pages', models.IntegerField()),
                ('is_new', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
