# Generated by Django 5.2.8 on 2025-11-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_bookmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
    ]
