# Generated by Django 5.2.8 on 2025-11-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_rename_bookmodel_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
