# Generated by Django 5.2.8 on 2025-11-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('color', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('is_new', models.BooleanField()),
            ],
        ),
    ]
